aws/aws-lambda-builders

- lambda_builders/actions/python_pip/DESIGN.md
Initial draft of Python PIP builder design doc. Let me know what you think.
> Initial draft of Python PIP builder design doc

- aws_lambda_builders/workflows/python_pip/workflow.py
- tests/integration/workflows/python_pip/test_python_pip.py
#19
Ignoring some common files when copying source for `python_pip` workflow
> Ignoring common Python files 

- Makefile
- aws_lambda_builders/workflows/python_pip/workflow.py
- tests/functional/test_utils.py
And, I also added functional test for `copytree` functionality
> Adding more files to python_pip ignores

- MANIFEST.in
- requirements/python_pip.txt
- setup.py
#31 and #29 
`python_pip` packager depends on setuptools and wheel to be available in environment. Ideally we would install these requirements into the target Python version we build, but to help the 80% of the case where they had pip installed this library, I am including the dependency directly here. 
This also helps when you install the library inside a Docker container that uses a Python version that doesn't come with wheel.
> Adding wheel dependency for python_pip packager

- aws_lambda_builders/__init__.py
- aws_lambda_builders/workflows/python_pip/packager.py
These debug log messages were super helpful when I was trying to debug #31 
> Adding debug logging to python_pip builder

- .appveyor.yml
- .travis.yml
- aws_lambda_builders/validate.py
- aws_lambda_builders/workflows/python_pip/actions.py
- aws_lambda_builders/workflows/python_pip/compat.py
- aws_lambda_builders/workflows/python_pip/packager.py
- tests/functional/workflows/python_pip/test_packager.py
- tests/integration/workflows/python_pip/test_python_pip.py
- tests/unit/workflows/python_pip/test_actions.py
- tests/unit/workflows/python_pip/test_packager.py
Lambda supports Python 3.7. Adding support for building Py37 functions in the builder.
Tested this change locally by running integration tests in Python 3.7
> Python 37 support

- aws_lambda_builders/workflows/python_pip/DESIGN.md
*Issue #, if available:* N/A
The `DESIGN.md` file contained a typo: "top-levle" vs "top-level".
> Fixed a typo

- requirements/dev.txt
Travis started failing for Py3.6 and up. Fix similar to https://github.com/awslabs/aws-sam-cli/pull/795
> fix: astroid version compatible to be compatible with pylint1.7

- aws_lambda_builders/exceptions.py
- aws_lambda_builders/validate.py
- tests/integration/workflows/python_pip/test_python_pip.py
- tests/unit/test_runtime.py
* When trying to build python2.7 lambda applications from within a sam installation housed in a python3.6 environment, one sees the following error message.
```bash
(venv) srirammv@localrainbow:~/sam-app$sam build
2018-11-26 13:40:16 Building resource 'HelloWorldFunction'
Build Failed
Error: python executable found in your path does not match runtime.
Expected version: python2.7, Found version: python3.6.
Consider moving python2.7 up path hierarchy.
Possibly related: https://github.com/awslabs/aws-lambda-builders/issues/30
```
Fixing this involves following steps:
* Moving up python executable of version python2.7 on the path
```
export PATH=/usr/bin:$PATH
```
```
(venv) srirammv@localrainbow::~/sam-app$sam build
2018-11-26 13:58:56 Building resource 'HelloWorldFunction'
2018-11-26 …
```
> fix: helpful error messages when runtime mismatch for build

- designs/Path_Resolver_DESIGN.md
First pass of design to get comments from the community.
Introduction of two pluggable components.
* Path Resolver
* Runtime Validator
> Design: Path Resolver

- aws_lambda_builders/workflows/nodejs_npm/DESIGN.md
- aws_lambda_builders/workflows/nodejs_npm/actions.py
- aws_lambda_builders/workflows/nodejs_npm/utils.py
- aws_lambda_builders/workflows/nodejs_npm/workflow.py
- tests/functional/workflows/nodejs_npm/test_utils.py
- tests/integration/workflows/nodejs_npm/test_nodejs_npm.py
- tests/integration/workflows/nodejs_npm/testdata/npmrc/.npmrc
- tests/integration/workflows/nodejs_npm/testdata/npmrc/excluded.js
- tests/integration/workflows/nodejs_npm/testdata/npmrc/included.js
- tests/integration/workflows/nodejs_npm/testdata/npmrc/package.json
- tests/unit/workflows/nodejs_npm/test_actions.py
- tests/unit/workflows/nodejs_npm/test_workflow.py
NPM can be configured to use proxies or local company repositories using a local file, `.npmrc`. 
The packaging process from step 1 normally excludes this file, so it needs to be copied before dependency installation, and then removed. 
> Extend Node.js NPM support for .npmrc configuration

- .appveyor.yml
Pins bundled version on AppVeyor. 
AppVeyor drops out with:
```
ERROR:  Error installing bundler:
The last version of bundler (>= 0) to support your Ruby & RubyGems was 1.17.3. Try installing it with `gem install bundler -v 1.17.3`
bundler requires RubyGems version >= 3.0.0. The current RubyGems version is 2.7.8. Try 'gem update --system' to update RubyGems itself.
```
> Updates bundler in AppVeyor

- aws_lambda_builders/workflows/go_dep/DESIGN.md
Creates a design doc for go-dep builder, it was omitted from the original PR.
> GoDep Design doc

- setup.py
Previously we were adding the complete license into the `license` key in `setup()`. This cause a corruption of the METADATA file that exist within the packaged `whl` or `tar` file. PyPi uses this file to render the homepage for the project and pip uses this for validation locally (should it install into X python version for example).
> fix: update license key in setup() to expected value by PyPi

- aws_lambda_builders/workflows/go_dep/workflow.py
- aws_lambda_builders/workflows/go_modules/workflow.py
- tests/integration/workflows/go_dep/test_go_dep.py
- tests/integration/workflows/go_modules/test_go.py
- tests/unit/workflows/go_dep/test_workflow.py
- tests/unit/workflows/go_modules/test_workflow.py
> refactor(go): Updated handler to output_executable_name for go workflows

- .appveyor.yml
- aws_lambda_builders/__init__.py
- aws_lambda_builders/__main__.py
- aws_lambda_builders/builder.py
- aws_lambda_builders/path_resolver.py
- aws_lambda_builders/utils.py
- aws_lambda_builders/workflow.py
- tests/functional/test_builder.py
- tests/functional/test_cli.py
- tests/functional/test_utils.py
- tests/unit/test_builder.py
- tests/unit/test_workflow.py
- search for executables on additional paths that are not on `$PATH`
- additional paths take precedence before searching for executables
on `$PATH`
- rev protocol version to 0.2 with introduction of additional search
paths.
https://github.com/awslabs/aws-lambda-builders/issues/77
> feat: allow path resolver to look at additional paths

- aws_lambda_builders/__main__.py
- tests/functional/test_cli.py
- bugfix: make executable_search_paths computable if not specified and add it as
`None`.
- explicitly check with a test with older RPC version and removal of
`executable_search_paths` param.
- This ensures that if the container is upgraded to the latest version of builders, and we build on the container from a older version of SAM CLI, back compat does not break.
> backcompat: cli

- aws_lambda_builders/workflows/python_pip/packager.py
- tests/unit/workflows/python_pip/test_packager.py
When packaging the dependencies only the first local package would be
included in the final bundle. This change adds support for any number
of local directory links to be treated as buildable dependencies. Tests
were also added for the case of 1 or 2 local directory links specified
in the requirements.txt.
> Fix local package installation

- setup.py
N/A
Python wheels, `.whl` files, produced through `python setup.py bdist_wheel` do not read or understand `MANIFEST.in` files. Since we use this file to remove tests modules from the dists, tests end up in the `.whl` files that get uploaded to PyPi. This PR updates the `exclude` parameter in `find_packages` to exclude all `test.*` modules, following [setuptools documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages).
> fix: Remove tests from .whl file (bdist_wheel)

- aws_lambda_builders/__init__.py
> chore: version bump to 0.2.0

- aws_lambda_builders/workflows/java_maven/maven.py
- tests/unit/workflows/java_maven/test_maven.py
https://github.com/awslabs/aws-sam-cli/issues/1056
Look at stdout stream instead of stderr stream to capture maven errors.
Below is a maven template whose pom.xml is looking for a non existent version of junit.
```
(aws_sam_cli_WS) srirammv@localrainbow:13:40:41:~/sam_init_maven/sam-app$sam build
2019-03-12 13:41:03 Building resource 'HelloWorldFunction'
2019-03-12 13:41:04 Running JavaMavenWorkflow:CopySource
2019-03-12 13:41:04 Running JavaMavenWorkflow:MavenBuild
Build Failed
Error: JavaMavenWorkflow:MavenBuild - Maven Failed:
```
```
(aws_sam_cli_WS) srirammv@localrainbow:13:40:41:~/sam_init_maven/sam-app$sam build
2019-03-12 13:41:03 Building resource 'HelloWorldFunction'
2019-03-12 13:41:04 Running JavaMavenWorkflow:CopySource …
```
> fix: maven builder logs

- aws_lambda_builders/workflows/java_maven/DESIGN.md
- aws_lambda_builders/workflows/java_maven/actions.py
- aws_lambda_builders/workflows/java_maven/maven.py
- tests/unit/workflows/java_maven/test_actions.py
- tests/unit/workflows/java_maven/test_maven.py
On Windows, the echo command is not valid in most cases. The Maven Workflow
was doing some operations that help support the multiple project build
use-case. Given this sometimes fails on Windows, the PR updates the Maven
Worklfow to only install and copy dependencies. This removes the need
to echo and therefore allows Windows Maven builds to succeed without
needing to run within the container.
Will solve https://github.com/awslabs/aws-sam-cli/issues/1053, when released within SAM CLI.
> fix: Remove MODULE_NAME command from Maven Workflow

- .appveyor.yml
- aws_lambda_builders/workflows/go_modules/validator.py
- tests/unit/workflows/go_modules/test_validator.py
https://github.com/awslabs/aws-lambda-builders/issues/92
- Fix version checks on go binary.
> fix: go validator

- aws_lambda_builders/workflows/java_maven/maven_validator.py
- tests/unit/workflows/java_maven/test_maven_validator.py
Use non-greedy match in the regular expression, to handle the case of `mvn -version` provided the major part of java version only.
> fix: match correct java version when only major version provided (#104)

- aws_lambda_builders/workflows/python_pip/actions.py
- tests/unit/workflows/python_pip/test_actions.py
N.A.
Most classes seem to follow this parameter pattern: `(artifacts_dir, scratch_dir, manifest_path) `
The PythonPipWorkflow class constructs the PythonPipBuildAction  with this order of arguments: `(artifacts_dir, scratch_dir, manifest_path, runtime)`
<https://github.com/awslabs/aws-lambda-builders/blob/29f254bc655c84b6ae651eee556787cb1cb5875c/aws_lambda_builders/workflows/python_pip/workflow.py#L67-L68>
The PythonPipBuildAction class has the following parameter order for its constructor: `(artifacts_dir, manifest_path, scratch_dir, runtime)`, which flips the `scratch_dir` & `manifest_path` arguments.
<https://github.com/awslabs/aws-lambda-builders/blob/29f254bc655c84b6ae651eee556787cb1cb5875c/aws_lambda_builders/workflows/python_pip/act …
> Fix order of `scratch_dir` & `manifest_path` parameters in python_pip workflow

- aws_lambda_builders/utils.py
WindowsError is a subclass of `OSError`. It is defined and raised only
in Windows. Hence the exception statement will return a
`WindowsError keyword is undefined` in other platforms.
EDIT: Usually this error is encountered when `CodeUri: /folder/does/not/exist`. The builder tries to copy the files and fails because the path does not exist. On Windows, the exception handler works, but on Mac/Linux Python interpreter does not find the variable `WindowsError` and crashes. So it leads to a vague `WindowsError` on Mac/Linux.
> fix: WindowsError keyword is undefined on non-Windows platforms

- CONTRIBUTING.md
Question on how to testing with SAM CLI was asked in #116
Updates the `CONTRIBUTING.md` guide on how to test with the local `aws-lambda-builders` changes.
> docs(contributing): Explain steps to test locally with SAM CLI

- aws_lambda_builders/workflows/java_maven/workflow.py
- tests/unit/workflows/java_maven/test_workflow.py
This causes issues on Windows machines due to file handles not being released
Added .git to the list of excluded files, similar to the python one which has additional files.
.git causes "WindowsError: [Error 5] Access is denied: c:\\temp\\.git\\objects\\*"
> Ignore .git files

- aws_lambda_builders/workflows/python_pip/compat.py
- aws_lambda_builders/workflows/python_pip/packager.py
- tests/unit/workflows/python_pip/test_packager.py
- if pip version is less than 19.3, choose to run `pip.main` directly as its a
function, whereas with pip versions starting with 19.3, execute the
function `main` inside the pip.main module
> fix: change the pip runner string based on a pip version check

- aws_lambda_builders/workflows/python_pip/compat.py
* Issue: awslabs/aws-sam-cli#1461 (original issue); awslabs/aws-lambda-builders#132 (PR fixing the issue)
This is a followup for awslabs/aws-lambda-builders#132.  The current fix for pip 19.3+ only works for all releases of pip with a minor version >= 3.  It will fail again with pip 20.0.
> fix: Do not revert to old broken import for pip 20+.[0-2]

- aws_lambda_builders/workflows/dotnet_clipackage/actions.py
- aws_lambda_builders/workflows/go_modules/builder.py
- aws_lambda_builders/workflows/go_modules/workflow.py
- tests/unit/workflows/go_modules/test_builder.py
Required to do IDE debugging of Go functions.
> feat:Add Go Modules Debug Build Flags

- setup.py
N/A
I noticed that the version of Lambda Builders was the whole file. This gets tracked back to when we added
```
>>> re.search(r"__version__ = \"([^'\"]+)", content).group(1)
'0.6.0'
>>> re.search(r"__version__ = \"([^']+)\"", content).group(1)
'0.6.0"\nRPC_PROTOCOL_VERSION = "0.3'
```
This did not happen before because the `__version__` was a string in single quotes and `RPC_PROTOCOL_VERSION` was double quotes. https://github.com/awslabs/aws-lambda-builders/commit/557214b5afff48d93e761d7286dd12c89ec8dc82#diff-eeb75f3f96c23565c44aae048349b2a3 Our regex at that time, assumed only version was the only thing in single quotes in the file (`aws_lambda_builders/__init__.py`). When we updated to standardize strings to be all double quotes with …
> fix: Regex for getting aws_lambda_builders version

- .appveyor.yml
- .gitignore
- aws_lambda_builders/workflow.py
- aws_lambda_builders/workflows/python_pip/actions.py
- aws_lambda_builders/workflows/python_pip/compat.py
- aws_lambda_builders/workflows/python_pip/exceptions.py
- tests/functional/testdata/cwd.py
- tests/integration/workflows/go_modules/test_go.py
- tests/integration/workflows/python_pip/test_python_pip.py
- tests/unit/test_workflow.py
- tests/unit/workflows/python_pip/test_actions.py
- tests/unit/workflows/python_pip/test_packager.py
Why is this change necessary?
* Generic "Binary Validation Failed" does not add enough value
How does it address the issue?
* Showcases which binary has failed and shows which paths were looked
at.
What side effects does this change have?
* None.
> fix: better error messages on build failures

- aws_lambda_builders/workflows/nodejs_npm/actions.py
Hi,
*Issue*
If `prepack` script is defined `npm` seems to output more than expected in original code.
`npm pack` outputs filename as last line of stdout, while in code the whole its output was assigned to `tarfile_name` var. This fix makes it right.
Thanks,
Alex
p.s. By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
> fix: npm output handling

- .appveyor.yml
Why is this change necessary?
* New minor versions of python updated in the appveyor images.
> fix: appveyor configuration

- aws_lambda_builders/workflows/dotnet_clipackage/actions.py
- tests/unit/workflows/dotnet_clipackage/test_actions.py
Please refer to this issue I created: https://github.com/awslabs/aws-sam-cli/issues/1970
Summary: when users have private feeds configured on their machines, the sam build command will fail because the dotnet cli tries to reference private feeds configured in the machine's global Nuget.Config
Adding the --ignore-failed-sources flag (e.g. dotnet tool install "Amazaon.Lambda.Tools" -g --ignore-failed-sources) fixes the issue.
> --ignore-failed-sources flag fix sam build error

- .gitignore
- aws_lambda_builders/workflows/dotnet_clipackage/dotnetcli.py
- aws_lambda_builders/workflows/dotnet_clipackage/utils.py
- tests/integration/workflows/custom_make/test_custom_make.py
*Issues
https://github.com/awslabs/aws-lambda-builders/issues/184
https://github.com/awslabs/aws-sam-cli/issues/2031
https://github.com/awslabs/aws-sam-cli/issues/1164
https://github.com/aws/aws-toolkit-vscode/issues/1144
aws dotnet extension output encoding is Console.OutputEncoding which is not UTF-8 in Windows(with utf8 beta option turned off).
Changed decoding to match the extension's system locale dependent encoding.
> Changed dotnet Encoding to System Locale Dependent

- aws_lambda_builders/workflows/ruby_bundler/bundler.py
- tests/unit/workflows/ruby_bundler/test_bundler.py
- relevant error information is in stdout instead of stderr for bundler.
Issue: https://github.com/awslabs/aws-sam-cli/issues/939
> fix(ruby): use stdout stream to raise exceptions from bundler

- .appveyor.yml
- .pre-commit-config.yaml
- Makefile
- requirements/dev.txt
- tests/functional/workflows/provided_make/test_utils.py
- tests/unit/test_builder.py
Manage black in dev.txt, almost the same as https://github.com/aws/serverless-application-model/pull/1748
> Manage black version using requirement file

- .appveyor.yml
Refer to https://github.com/aws/aws-sam-cli/pull/2386:
When AppVeyor updates their python env, like from 3.7.7 to 3.7.9, 3.7.7 won't be available, and builds will fail due to the error:
```
/opt/appveyor/build-agent/bash-shell.sh: line 51: /home/appveyor/venv3.7.7/bin/activate: No such file or directory
```
According to AppVeyor doc, we don't have to specify patch version: https://www.appveyor.com/docs/linux-images-software/#python
> chore: Remove python patch version in AppVeyor to be more robust

- .pylintrc
- aws_lambda_builders/workflows/custom_make/DESIGN.md
- aws_lambda_builders/workflows/python_pip/packager.py
- tests/functional/workflows/python_pip/test_packager.py
Remove biased language from this repo.
> chore: Remove biased language

- aws_lambda_builders/workflows/dotnet_clipackage/actions.py
- tests/unit/workflows/dotnet_clipackage/test_actions.py
https://github.com/aws/aws-lambda-builders/issues/211
This change is adding a lock and an installation flag to GlobalToolInstallAction, to run it only once when it has run in a parallel build process.
> fix: run GlobalToolInstallAction in a lock block and only once

- .appveyor.yml
- aws_lambda_builders/workflows/python_pip/compat.py
- aws_lambda_builders/workflows/python_pip/packager.py
- aws_lambda_builders/workflows/python_pip/utils.py
- aws_lambda_builders/workflows/python_pip/validator.py
https://github.com/aws/aws-lambda-builders/issues/224
Patches the LB_LIBRARY_PATH envar and passes the original one to all popens in Python workflow.
This is required as PyInstaller changes LB_LIBRARY_PATH and affects its subprocesses.
> fix: Python Workflow with Incorrect Environ

- aws_lambda_builders/workflows/python_pip/packager.py
- tests/functional/workflows/python_pip/test_packager.py
- tests/unit/workflows/python_pip/test_packager.py
Prevent already downloaded dependencies from hanging the download process (it's waiting for user input)
If your build depends on two private repos, for example your `requirements.txt` has:
```
git+ssh://git@github.com/org/package_1.git#package_1
git+ssh://git@github.com/org/package_2.git#package_2
```
and `package_2` depends on `package_1` in it's own `requirements.txt`, the build process hangs. It waits for user input, to decide how to deal with the existing downloaded `package_1`. This commit should provide a sensible default behaviour.
> Prevent already downloaded dependencies from hanging the download

- aws_lambda_builders/workflows/go_modules/builder.py
- tests/unit/workflows/go_modules/test_builder.py
Compiling Go binaries without optimizations was not working. This is because "-gcflags='all=-N -l'" is not actually a valid argument to be passed to the executable. The equal sign should be treated as an argument separator, so a shell would parse this to  "-gcflags" and "all=-N -l".
> Fix Go debug mode

- DESIGN.md
- README.md
Solves #235 
* Improved the main [design document](DESIGN.md)
to explain integration via the JSON-RPC 2.0 interface
* Added a reference to the design document
for developers intending to integrate to Lambda Builders
> docs: Guidance on integrating with Lambda Builders

- aws_lambda_builders/workflows/python_pip/packager.py
- tests/functional/workflows/python_pip/test_packager.py
- tests/integration/workflows/python_pip/test_python_pip.py
- tests/integration/workflows/python_pip/testdata/local-dependencies/hello_world/requirements.txt
- tests/integration/workflows/python_pip/testdata/local-dependencies/setup.cfg
- tests/integration/workflows/python_pip/testdata/local-dependencies/setup.py
- tests/integration/workflows/python_pip/testdata/local-dependencies/some_package/setup.py
- tests/integration/workflows/python_pip/testdata/local-dependencies/src/local_package/entrypoint.py
- tests/unit/workflows/python_pip/test_packager.py
*Which issue(s) does this change fix?*
https://github.com/aws/aws-sam-cli/issues/2705
*Why is this change necessary?*
Fix local dependencies not being resolved by pip.
*How does it address the issue?*
Looks like [pip updated the output](https://github.com/pypa/pip/commit/b28e2c4928cc62d90b738a4613886fb1e2ad6a81#diff-5225c8e359020adb25dfc8c7a505950fd649c6c5775789c6f6517f7913f94542L529) that we try to string match, meaning we weren't catching local packages for newer versions of pip. 
This change adds multiple layers of regex matching to include both the old and new output format.
*What side effects does this change have?*
*Checklist:*
> fix: Pip not resolving local packages

- .appveyor.yml
- DESIGN.md
- README.md
- aws_lambda_builders/__init__.py
- aws_lambda_builders/workflows/python_pip/packager.py
- aws_lambda_builders/workflows/python_pip/workflow.py
- aws_lambda_builders/workflows/ruby_bundler/bundler.py
- aws_lambda_builders/workflows/ruby_bundler/utils.py
- tests/functional/workflows/ruby_bundler/test_ruby_utils.py
- tests/integration/workflows/python_pip/test_python_pip.py
- tests/integration/workflows/python_pip/testdata/local-dependencies/setup.cfg
- tests/integration/workflows/python_pip/testdata/local-dependencies/setup.py
- tests/integration/workflows/python_pip/testdata/local-dependencies/src/local_package/entrypoint.py
- tests/integration/workflows/ruby_bundler/test_ruby.py
- tests/integration/workflows/ruby_bundler/testdata/excludes-gemfile/handler.rb
- tests/unit/workflows/python_pip/test_packager.py
- tests/unit/workflows/python_pip/test_workflow.py
- tests/unit/workflows/ruby_bundler/test_bundler.py
> Merge develop into master

- .appveyor.yml
- aws_lambda_builders/workflows/python_pip/packager.py
- aws_lambda_builders/workflows/python_pip/validator.py
- tests/integration/workflows/python_pip/test_python_pip.py
- tests/unit/workflows/python_pip/test_packager.py
- tests/unit/workflows/python_pip/test_validator.py
* Adding python39 support
* changing Visual Studio image from 2017 to Visual Studio 2019
* update Appveyor to solve make pr failure
* update packager.py
> runtime: Add python3.9 support

- aws_lambda_builders/workflows/python_pip/packager.py
- aws_lambda_builders/workflows/python_pip/utils.py
- tests/functional/workflows/python_pip/test_packager.py
* A pep517 build can declare build dependencies. Pip will then
know to install these dependencies before trying to build a wheel
file.
* When creating a build environment, it's only guaranteed to last
for the duration of the build process. It's not accessible once
a pip command finishes running.
* When we try to retrieve the version of a package we run a "modified"
form of "python setup.py egg_info".
* The problem with this is that we're not using the build environment
that has all the build dependencies installed (it's already gone),
so if setup.py imports a module (e.g. cython) because it expects
it to be there because it declared it as a build dependency
the egg_info command will fail.
* We don't check the RC or have a fallback case if we can't generate
egg info.
* We fail with an …
> fix: improve support for pep517 builds

- aws_lambda_builders/__main__.py
- aws_lambda_builders/builder.py
- aws_lambda_builders/workflow.py
- tests/functional/test_cli.py
- tests/unit/test_builder.py
> feat: Adding New Parameters

- aws_lambda_builders/__init__.py
> chore: aws lambda builders version set to 1.7.0

- aws_lambda_builders/actions.py
- aws_lambda_builders/workflows/nodejs_npm/workflow.py
- aws_lambda_builders/workflows/ruby_bundler/workflow.py
- tests/integration/workflows/nodejs_npm/test_nodejs_npm.py
- tests/integration/workflows/ruby_bundler/test_ruby.py
- tests/unit/test_actions.py
- tests/unit/workflows/nodejs_npm/test_workflow.py
- tests/unit/workflows/ruby_bundler/test_workflow.py
> feat/Node and Ruby Dependency Dir and Download Dependency

- tests/integration/workflows/python_pip/test_python_pip.py
> test: Temporarily disabling two Python integration tests failing on Windows

- aws_lambda_builders/workflows/nodejs_npm/workflow.py
- tests/integration/workflows/nodejs_npm/test_nodejs_npm.py
- tests/integration/workflows/nodejs_npm/testdata/no-manifest/app.js
- tests/unit/workflows/nodejs_npm/test_workflow.py
> feat: Allow Node.js projects to be built without requiring a package.json

- aws_lambda_builders/workflows/go_modules/validator.py
> fix: remove rendundant get_go_versions method

- aws_lambda_builders/actions.py
- aws_lambda_builders/workflows/java_gradle/workflow.py
- aws_lambda_builders/workflows/java_maven/workflow.py
- aws_lambda_builders/workflows/nodejs_npm/workflow.py
- aws_lambda_builders/workflows/python_pip/workflow.py
- aws_lambda_builders/workflows/ruby_bundler/workflow.py
- tests/unit/test_actions.py
- tests/unit/workflows/java_gradle/test_workflow.py
- tests/unit/workflows/java_maven/test_workflow.py
- tests/unit/workflows/nodejs_npm/test_workflow.py
- tests/unit/workflows/python_pip/test_workflow.py
- tests/unit/workflows/ruby_bundler/test_workflow.py
add action for clean up the dependencies folder before installing/moving/copying
> [Auto Dependencies Layer] clean up dependencies action

- .github/labeler.yml
- .github/workflows/README.md
- .github/workflows/pr-labeler.yml
n/a
Adds a Github Action that auto labels PRs (similar to SAM and SAM CLI repos)
> Chore: Auto PR labeler

- aws_lambda_builders/actions.py
- tests/unit/test_actions.py
> fix: Added Create Directory before Copy

- aws_lambda_builders/workflows/java/actions.py
- tests/unit/workflows/java/test_actions.py
https://github.com/aws/aws-sam-cli/issues/3429
> fix: Updated TestJavaMoveDependenciesAction to Include lib Folder

- .appveyor.yml
- requirements/dev.txt
N/A
Fixing issue in appveyor jobs
- pin to newer black version
- remove `bzr` in Windows CI job
> Fix CI (appveyor) env

- aws_lambda_builders/workflows/custom_make/make.py
N/A
The Make builder does not log anything to stdout when it executes the make command. This change logs the output of the make command so developers can see the results of the execution. This follows the same pattern that exists in the `dotnetcli` builder.
> fix: log results of make build

- aws_lambda_builders/workflows/nodejs_npm_esbuild/DESIGN.md
- aws_lambda_builders/workflows/nodejs_npm_esbuild/esbuild.py
- tests/integration/workflows/nodejs_npm_esbuild/test_nodejs_npm_with_esbuild.py
- tests/unit/workflows/nodejs_npm_esbuild/test_actions.py
- tests/unit/workflows/nodejs_npm_esbuild/test_esbuild.py
Related to AWS SAM CLI change: https://github.com/aws/aws-sam-cli/pull/4062
This change changes source map's default value from `true` to `false`.
> feat: Changed Sourcemap default value to false

- aws_lambda_builders/exceptions.py
- aws_lambda_builders/path_resolver.py
- aws_lambda_builders/workflows/python_pip/workflow.py
- tests/integration/workflows/python_pip/test_python_pip.py
- tests/unit/test_path_resolver.py
- tests/unit/workflows/python_pip/test_workflow.py
n/a
* Lookup `python3` binary if the python runtime has a major version of 3.
> fix(path-resolver): Add additional binaries to python-pip workflow

- aws_lambda_builders/workflows/custom_make/actions.py
- aws_lambda_builders/workflows/custom_make/utils.py
- aws_lambda_builders/workflows/custom_make/workflow.py
- tests/integration/workflows/custom_make/test_custom_make.py
- tests/integration/workflows/custom_make/testdata/makefile-in-different-working-directory/Makefile
- tests/integration/workflows/custom_make/testdata/makefile-in-different-working-directory/source_code/main.py
- tests/integration/workflows/custom_make/testdata/makefile-in-different-working-directory/source_code/requirements-requests.txt
- tests/unit/workflows/custom_make/test_actions.py
- tests/unit/workflows/custom_make/test_workflow.py
Update the Custom builder workflow to accept a working directory within the options directory, to allow the custom builder to execute Makefile that exist outside the Lambda resources source code, or that run some building logic on a project level instead of lambda resource code path level.
> feat: add custom working directory for custom build workflow

- aws_lambda_builders/__init__.py
Bump aws-lambda-builders version to 1.19.0
> chore: bump version to 1.19.0

- .appveyor.yml
- aws_lambda_builders/workflows/nodejs_npm/actions.py
- aws_lambda_builders/workflows/nodejs_npm/workflow.py
- aws_lambda_builders/workflows/nodejs_npm_esbuild/esbuild.py
- aws_lambda_builders/workflows/nodejs_npm_esbuild/workflow.py
- tests/integration/workflows/nodejs_npm_esbuild/test_nodejs_npm_with_esbuild.py
- tests/integration/workflows/nodejs_npm_esbuild/testdata/esbuild-binary/package-lock.json
- tests/integration/workflows/nodejs_npm_esbuild/testdata/esbuild-binary/package.json
- tests/unit/workflows/nodejs_npm/test_actions.py
- tests/unit/workflows/nodejs_npm_esbuild/test_esbuild.py
- tests/unit/workflows/nodejs_npm_esbuild/test_workflow.py
> feat: Install esbuild deps with production flag

- aws_lambda_builders/workflows/nodejs_npm_esbuild/esbuild.py
- tests/unit/workflows/nodejs_npm_esbuild/test_esbuild.py
Options are passed to LB using snake-case and esbuild expects the argument in a dash-delimited case. This PR converts the options from first case to the second. 
> fix: Address main fields incorrectly inputted

- aws_lambda_builders/workflows/python_pip/workflow.py
- tests/unit/workflows/python_pip/test_workflow.py
Symlinking dependencies for python runtimes can't be used with `sam local` commands, disabling now until it is been fixed in SAM CLI.
Disable `LinkSourceAction` and use `CopySourceAction` instead.
> fix: disable symlinking for python dependencies

- .appveyor.yml
- aws_lambda_builders/workflows/go_modules/validator.py
- aws_lambda_builders/workflows/go_modules/workflow.py
N/A
I ran into this when trying to deploy a go function with the `arm64` platform. `go1.x` is `x86_64` only, so this requires the `provided.al2` runtime. The docs for the go runtime demonstrate [using the `Makefile` builder](https://docs.aws.amazon.com/lambda/latest/dg/golang-package.html#golang-package-al2) for using `provided.al2`. This works, but requires an extra project file compared to `go1.x`. I also saw in the docs that `BuildMethod` can be set the the value of a runtime, so tried that!
from: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html
> If a resource includes a Metadata resource attribute with a BuildMethod entry, sam build builds that resource according …
> Support go1.x builder with the provided.al2 runtime

- aws_lambda_builders/workflows/custom_make/make.py
- tests/unit/workflows/custom_make/test_make.py
https://github.com/aws/aws-sam-cli/issues/2006
Stream stdout as it happens, dump stderr if makefile builder errored out.
> fix: `Makefile` workflow to stream output

- aws_lambda_builders/workflows/dotnet_clipackage/actions.py
- aws_lambda_builders/workflows/dotnet_clipackage/utils.py
- tests/integration/workflows/dotnet_clipackage/test_dotnet.py
- tests/integration/workflows/dotnet_clipackage/testdata/CustomRuntime6/CustomRuntime6.csproj
- tests/integration/workflows/dotnet_clipackage/testdata/CustomRuntime6/Function.cs
- tests/integration/workflows/dotnet_clipackage/testdata/CustomRuntime6/aws-lambda-tools-defaults.json
- tests/unit/workflows/dotnet_clipackage/test_utils.py
*Description of changes:* 
Because of [this issue](https://bugs.python.org/issue15795), files coming back from Amazon.Lambda.Tools were not getting the same permissions after unzipping. In the case where we want to `sam local invoke` on a custom runtime, this means we'll get a permission error since the unzipped files don't have execute permissions. This uses the [code from SAM CLI](https://github.com/aws/aws-sam-cli/blob/develop/samcli/local/lambdafn/zip.py#L81) to set permissions correctly.
> Restore file permissions after unzip

- aws_lambda_builders/validator.py
- tests/integration/workflows/nodejs_npm/test_nodejs_npm.py
- tests/integration/workflows/nodejs_npm_esbuild/test_nodejs_npm_with_esbuild.py
> feat: nodejs18

- aws_lambda_builders/__init__.py
Bumping the Lambda Builders version from `1.23.0` to `1.23.1`.
> chore: Version bump from 1.23.0 to 1.23.1

- aws_lambda_builders/workflows/nodejs_npm/actions.py
- tests/integration/workflows/nodejs_npm_esbuild/test_nodejs_npm_with_esbuild.py
- tests/unit/workflows/nodejs_npm/test_actions.py
`npm 9.x` no longer packs the `npm-shrinkwrap.json` so we need to do it ourselves to respect this file during installation, similarly to how to copy over the `package-lock.json`.
> fix: Copy over shrinkwrap if it exists

- .github/workflows/build.yml
Have the new GitHub actions only run against the `develop` branch and only against this repository.
> chore: Update branch, repo for build/test action

- .github/workflows/build.yml
- tests/unit/test_builder.py
- Use the repository owner as the condition for running tests
- Create a parent job to require for accepting PRs instead of needing to manually add all 80 jobs
> test: Use Repo Owner Condition, Add Job Aggregation

- README.md
Badge changes;
- Current build badge doesn't reflect the actual status since we are only building for the PRs (not for the branch). And since there is now way to display build status for the latest PR, we are removing it.
- Adding license badge
- Adding latest version badge from GH releases
- Adding supported python versions badge from PyPI
- Adding library name for `pip` as static badge
Supported build changes;
- We removed `Go with Dep` with this PR: https://github.com/aws/aws-lambda-builders/pull/354
- Added latest esbuild support for Typescript
> chore: update badges and build support list in readme

- aws_lambda_builders/workflow.py
- aws_lambda_builders/workflows/custom_make/workflow.py
- aws_lambda_builders/workflows/dotnet_clipackage/workflow.py
- aws_lambda_builders/workflows/go_modules/workflow.py
- aws_lambda_builders/workflows/java_gradle/workflow.py
- aws_lambda_builders/workflows/java_maven/workflow.py
- aws_lambda_builders/workflows/nodejs_npm/workflow.py
- aws_lambda_builders/workflows/nodejs_npm_esbuild/workflow.py
- aws_lambda_builders/workflows/python_pip/workflow.py
- aws_lambda_builders/workflows/ruby_bundler/workflow.py
- tests/functional/testdata/workflows/hello_workflow/write_hello.py
- tests/unit/test_builder.py
- tests/unit/test_workflow.py
Building in source
- handles default values for each workflow
- handles supported values for each workflow
- ensures each workflow should define its own defaults and supported values
- error handling if the passed-in value is not supported by the workflow
> feat: handle default and supported values for building in source per workflow

- tests/integration/workflows/nodejs_npm_esbuild/test_nodejs_npm_with_esbuild.py
With npm version 9.3, the `npm ci` command now breaks when run. This seems like a bug with the newest version of npm. The `npm ci` command attempts to remove the existing `node_modules` directory but fails to do so if it contains a `.bin` directory, meaning and subsequent invocations of `npm ci` will fail. 
This PR replaces `npm ci` with `npm install` to unblock our integration tests.
> fix: Fix failing esbuild integration tests

- aws_lambda_builders/workflows/nodejs_npm_esbuild/esbuild.py
- tests/integration/workflows/nodejs_npm_esbuild/test_nodejs_npm_with_esbuild.py
- tests/unit/workflows/nodejs_npm_esbuild/test_esbuild.py
#426
Add support for the `--out-extension` flag for producing `.mjs` files to take advantage of es modules support.
> feat: Add support for mjs files with esbuild

- .github/ISSUE_TEMPLATE/bug_report.md
N/A
Main reason is for how we track bugs. We first want to validate the bug before adding the label.
> chore: Remove type/bug label for Bug Issue Template

- aws_lambda_builders/workflow.py
- aws_lambda_builders/workflows/custom_make/workflow.py
- aws_lambda_builders/workflows/dotnet_clipackage/workflow.py
- aws_lambda_builders/workflows/go_modules/workflow.py
- aws_lambda_builders/workflows/java_gradle/workflow.py
- aws_lambda_builders/workflows/java_maven/workflow.py
- aws_lambda_builders/workflows/nodejs_npm/workflow.py
- aws_lambda_builders/workflows/nodejs_npm_esbuild/workflow.py
- aws_lambda_builders/workflows/python_pip/workflow.py
- aws_lambda_builders/workflows/ruby_bundler/workflow.py
- tests/functional/testdata/workflows/hello_workflow/write_hello.py
- tests/unit/test_builder.py
- tests/unit/test_workflow.py
- tests/unit/workflows/custom_make/test_workflow.py
A recent change (https://github.com/aws/aws-lambda-builders/pull/418) added `BUILD_IN_SOURCE_BY_DEFAULT` to each workflow. This PR replaces that with `DEFAULT_BUILD_DIR`, which helps us generalize some logic more. We can now set and use a workflow's `build_dir` property using a combination of:
- the value of the `build_in_source` parameter passed in to lambda builders
- if user wants to build in source, the build directory should be set to the source directory
- the workflow's default build directory (`DEFAULT_BUILD_DIR`)
- in case `build_in_source` is not set, or it's set to `False`, or an unsupported value is passed in, we should use the workflow's existing default build directory
Note that we're still able to find out if a workflow …
> refactor: assign each workflow a default build directory

- aws_lambda_builders/workflows/nodejs_npm_esbuild/workflow.py
- tests/unit/workflows/nodejs_npm_esbuild/test_workflow.py
In the esbuild workflow, symlinking is needed when we are not installing dependencies and we already have a dependencies_dir, so that we can symlink that dependencies_dir (node_modules) before bundling. 
However, there's another part of the code that does symlinking when we already installed dependencies and we already bundled, so it shouldn't be necessary here. Moreover this symlink is created in the scratch directory, so it won't persist anyway.
> fix: remove unused symlinking in esbuild workflow

- aws_lambda_builders/workflows/dotnet_clipackage/utils.py
- aws_lambda_builders/workflows/python_pip/compat.py
- pyproject.toml
N/A
In #435, I added `ruff` to replace `pylint` linting. However, I missed that `ruff` does not add `pylint` in by default (only pycodestyle and Pyflakes. This PR targets `pylint` rules ruff has.
> chore: Enable pylint within ruff

- aws_lambda_builders/workflows/nodejs_npm/actions.py
- aws_lambda_builders/workflows/nodejs_npm/workflow.py
- aws_lambda_builders/workflows/nodejs_npm_esbuild/workflow.py
- tests/integration/workflows/nodejs_npm_esbuild/test_nodejs_npm_with_esbuild.py
- tests/unit/workflows/nodejs_npm_esbuild/test_workflow.py
Now that `build_dir` will point to either the source directory, if building in source, or the workflow's default build directory, we can refactor the workflow to use `build_dir` and it will enable build-in-source support.
> feat: use build_dir in esbuild workflow to support building in source

- .github/dependabot.yml
- requirements/dev.txt
- Pins the ruff version to ensure our CI jobs don't break unexpectedly
- Adds a `dependabot` config that runs weekly to check for newer dependency versions and raises a PR accordingly.
> feat: Pin ruff version, add dependabot config

- aws_lambda_builders/workflows/nodejs_npm_esbuild/esbuild.py
- tests/integration/workflows/nodejs_npm_esbuild/test_nodejs_npm_with_esbuild.py
- tests/unit/workflows/nodejs_npm_esbuild/test_esbuild.py
#438
Add support for the `--sources-content=false` option to create much more lightweight production sourcemaps that don't include the source code.
This change will require a documentation update.
> feat: Add sources content flag to supported esbuild options

- .github/workflows/build.yml
n/a
From Github docs, Workflows need to be trigger-able by the merge queue. I think this was why the merge queue was not working as expected. 
> chore: Enable workflow to trigger on merge_group

- tests/functional/workflows/python_pip/test_packager.py
This fixes https://github.com/aws/aws-lambda-builders/issues/474
setuptools 66.0.0 dropped support for PEP 440 non-conforming versions. A few of the unittests in this repo use versions that are not PEP 440 compatible. I changed them to be compatible, and now those tests pass =)
> Add compatibility with setuptools 66+

- .github/workflows/build.yml
Enable GHA CI jobs to run against `develop` and `feat*` branches.
> ci: add feat* rule to run github actions

- aws_lambda_builders/workflows/python_pip/packager.py
- tests/unit/workflows/python_pip/test_packager.py
#489 
Newer versions of `pip` updated the output of `pip download`, causing our local package logic to fail.
`pip 23.0`
```
...
Processing ./package_a
...
```
`pip 23.1`
```
...
Processing ./package_a (from 123==1.1.1->-r requirements.txt (line 1))
...
```
This change updates the regex to stop at a space, or a newline, which ever appears first.
> fix: Updated regex to match newer pip output

- Makefile
N/A
Adds a Makefile target to make formatting with black and ruff easier.
> feat: Add format target to makefile

- aws_lambda_builders/workflows/dotnet_clipackage/actions.py
- tests/integration/workflows/dotnet_clipackage/testdata/CustomRuntime6/aws-lambda-tools-defaults.json
- tests/unit/workflows/dotnet_clipackage/test_actions.py
This change made:
1. To complete support for building ARM64 dotnet7 functions https://github.com/aws/aws-sam-build-images/pull/81. Pass down directly the `Architecture` parameter defined in SAM template to Amazon Lambda Tools via `--function-architecture` argument. Previously when building dotnet7 functions, users  also need to make changes in `aws-lambda-tools-defaults.json` in their source code directories.
> Add function architecture argument when building dotnet function 

- aws_lambda_builders/__init__.py
Bump Lambda builders version to 1.32.0 to prepare for the Ruby 3.2 release.
> chore: version bump to 1.32.0

- aws_lambda_builders/workflows/nodejs_npm_esbuild/esbuild.py
- tests/integration/workflows/nodejs_npm_esbuild/test_nodejs_npm_with_esbuild.py
- tests/unit/workflows/nodejs_npm_esbuild/test_actions.py
https://github.com/aws/aws-sam-build-images/issues/90
https://github.com/aws/aws-sam-cli/issues/5236
Since making the change to accept any flags for esbuild, there is an issue with esbuild trying to use flags that are not related to it. This changes forces the esbuild command builder to ignore those unrelated flags.
> fix: Ignore flags not relevant to esbuild

- aws_lambda_builders/actions.py
- aws_lambda_builders/workflows/nodejs_npm/workflow.py
- aws_lambda_builders/workflows/nodejs_npm_esbuild/workflow.py
- tests/integration/workflows/nodejs_npm/test_nodejs_npm.py
- tests/integration/workflows/nodejs_npm/testdata/manifest-outside-root-with-local-dependency/manifest/package.json
- tests/integration/workflows/nodejs_npm/testdata/manifest-outside-root-with-local-dependency/src/excluded.js
- tests/integration/workflows/nodejs_npm/testdata/manifest-outside-root-with-local-dependency/src/included.js
- tests/integration/workflows/nodejs_npm/testdata/manifest-outside-root/manifest/package.json
- tests/integration/workflows/nodejs_npm/testdata/manifest-outside-root/src/excluded.js
- tests/integration/workflows/nodejs_npm/testdata/manifest-outside-root/src/included.js
- tests/integration/workflows/nodejs_npm_esbuild/test_nodejs_npm_with_esbuild.py
- tests/integration/workflows/nodejs_npm_esbuild/testdata/esbuild-manifest-outside-root-with-local-depends/manifest/package.json
- tests/integration/workflows/nodejs_npm_esbuild/testdata/esbuild-manifest-outside-root-with-local-depends/src/included.ts
- tests/integration/workflows/nodejs_npm_esbuild/testdata/esbuild-manifest-outside-root/manifest/package.json
- tests/integration/workflows/nodejs_npm_esbuild/testdata/esbuild-manifest-outside-root/src/included.ts
- tests/unit/test_actions.py
- tests/unit/workflows/nodejs_npm/test_workflow.py
- tests/unit/workflows/nodejs_npm_esbuild/test_workflow.py
https://github.com/aws/aws-sam-cli/issues/4832, I also found that this issue exist in the NPM build.
For NPM Build:
- added an action to copy the source code files to artifact directory in case if the passed manifest is in a different directory, as the used NPM Pack Action does not copy the source code files.
- Run the NPM Install Action to run on the manifest directory if it exist outside the source code, and building in source. This action will enable supporting local dependencies. Then link the `node_modules` from the manifest directory to the source code directory.
For ESBuild:
- added an action to copy the manifest directory content to build directory in case if the passed manifest is in a different directory, and the customer is not …
> fix: Enable --manifest flag for esbuild and npm build

- aws_lambda_builders/__init__.py
bump lambda builders version to 1.35.0 to prepare for the 1.35.0 release 
> chore: Version bump to 1.35.0

- aws_lambda_builders/workflow.py
- aws_lambda_builders/workflows/custom_make/actions.py
5369
Use logical_build_id that is passed from SAM_CLI to support better logging for parallel build logs.
> Unordered parallel build logs

- aws_lambda_builders/workflows/custom_make/make.py
N/A
Some of the output that may come from a Makefile (eg. Terraform output) can contain some colour and encoding information (eg. `b'\x1b[0m\x1b[1mInitializing provider plugins...\x1b[0m\n' `). This does not get logged properly in the terminal.
Changes are to use `sys.stderr.buffer.write()` to print these messages instead.
> fix: Fix missing encoding when logging from Makefile

- aws_lambda_builders/workflows/python_pip/packager.py
*Issue #, if available:
https://github.com/aws/aws-sam-cli/issues/3747
Hey team,
We encountered an issue building cross-platform for `arm64` outside of a container with `sam build`:
```
Build Failed
Error: PythonPipBuilder:ResolveDependencies - {grpcio==1.57.0(wheel)}
```
**grpcio** does indeed have a wheel available in PyPI at `..._manylinux_2_17_aarch64.whl`, but **aws-sam-cli** is currently only able to resolve the `manylinux_2_17` tags for `x86_64` wheels.
This PR adds the alias in [PEP 600](https://peps.python.org/pep-0600/#legacy-manylinux-tags) for `manylinux2014_aarch64 -> manylinux_2_17_aarch64`.
> Support PEP 600 platform tags for arm64

- aws_lambda_builders/workflows/nodejs_npm_esbuild/workflow.py
- tests/unit/workflows/nodejs_npm_esbuild/test_workflow.py
N/A
The workflow currently looks at the scratch directory to determine if esbuild is present or not. This is not the case for build in source however, as the Node modules are installed in the source directory, not the scratch directory.
This change updates the path to be `build_dir`, which is already set to the correct folder from earlier in the workflow.
> fix: Update esbuild binary fetching logic to look inside of `build_dir`

- aws_lambda_builders/utils.py
- aws_lambda_builders/workflows/dotnet_clipackage/dotnetcli.py
- aws_lambda_builders/workflows/dotnet_clipackage/utils.py
- aws_lambda_builders/workflows/java_gradle/gradle_validator.py
- aws_lambda_builders/workflows/java_maven/maven.py
- tests/unit/test_utils.py
#548 
https://github.com/aws/aws-sam-cli/issues/2317
There are times when Lambda Builders will attempt to decode command output that contains unsupported characters. In these events, the program will crash with an unhandled exception. Instead, complete the build and log a message explaining that the output couldn't be decoded.
> fix: Decoding non-unicode characters raises unhandled exception

- aws_lambda_builders/workflows/ruby_bundler/bundler.py
- tests/unit/workflows/ruby_bundler/test_bundler.py
[#6068](https://github.com/aws/aws-sam-cli/issues/6068)
the stderr output of the subprocess was being ignored and because of this if there was no information in stdout all that a user would see was that the bundler failed.
This fix has the bundler output the stderr from the subprocess if it fails.
> fix: streaming stderr from subprocess started by lambda-builders

- aws_lambda_builders/actions.py
- aws_lambda_builders/utils.py
- tests/unit/test_actions.py
- tests/unit/test_utils.py
N/A
There are two scenarios fixed by this PR:
1. The symbolic link action attempts to link to a non-existent directory. This results in an error when executing `sam package`.
2. The symbolic link utility function attempts to link to an already created directory resulting in an error when using auto-dependency layer.
> fix: Symlinks to non-existent directories, symlinks re-creating

- aws_lambda_builders/actions.py
- aws_lambda_builders/workflows/nodejs_npm/actions.py
- aws_lambda_builders/workflows/nodejs_npm/workflow.py
- aws_lambda_builders/workflows/nodejs_npm_esbuild/workflow.py
- tests/integration/workflows/nodejs_npm/test_nodejs_npm.py
- tests/unit/workflows/nodejs_npm/test_workflow.py
- tests/unit/workflows/nodejs_npm_esbuild/test_workflow.py
N/A
When `--build-in-source` is used, `npm install` command won't remove any dependency that is removed between 2 invocations.
This PR addresses that by adding `NodejsNpmUpdateAction` and using it when build-in-source is enabled which runs `npm --no-audit --no-save --unsafe-perm --production --no-package-lock --install-links`.
`--install-links` flag is also removed from `NodejsNpmInstallAction` which was only used for build in source workflow.
> fix: use npm update when building in source

- .github/workflows/close-issue-on-release.yml
Adds a new GHA which will run when a release completes to close all issues with `stage/waiting-for-release` label with following message;
> Patch is released in [{release_version}](release_url). If you are AWS SAM CLI user, please wait for next AWS SAM CLI release. Closing
> chore: auto close issues with stage/waiting-for-release tag when a new release is completed

- aws_lambda_builders/__init__.py
bumps the version of lambda builders to the next version
> Chore: bump version to 1.44

- aws_lambda_builders/validator.py
- tests/integration/workflows/nodejs_npm/test_nodejs_npm.py
- tests/integration/workflows/nodejs_npm_esbuild/test_nodejs_npm_with_esbuild.py
- tests/unit/workflows/nodejs_npm_esbuild/test_actions.py
- tests/unit/workflows/nodejs_npm_esbuild/test_esbuild.py
N/A
Remove runtimes deprecated by Lambda.
> chore: Deprecate nodejs12.x and nodejs14.x

- .github/workflows/build.yml
- aws_lambda_builders/validator.py
- aws_lambda_builders/workflows/ruby_bundler/DESIGN.md
- tests/integration/workflows/ruby_bundler/test_ruby.py
Removes `ruby2.7` support for the library and for building lambda functions.
> chore: remove ruby2.7 runtime support

- .github/workflows/build.yml
- aws_lambda_builders/validator.py
- aws_lambda_builders/workflows/python_pip/DESIGN.md
- aws_lambda_builders/workflows/python_pip/packager.py
- requirements/dev.txt
- setup.py
- tests/integration/workflows/python_pip/test_python_pip.py
- tests/integration/workflows/python_pip/testdata/requirements-numpy.txt
- tests/unit/test_validator.py
- tests/unit/test_workflow.py
- tests/unit/workflows/python_pip/test_packager.py
- tests/unit/workflows/python_pip/test_validator.py
https://github.com/aws/aws-sam-cli/issues/6298
Removes `python3.7` support for the library and for building lambda functions.
> fix: remove python3.7 support

- aws_lambda_builders/workflows/go_modules/workflow.py
- tests/integration/workflows/go_modules/test_go.py
- tests/unit/workflows/go_modules/test_workflow.py
https://github.com/aws/aws-sam-cli/issues/6635
For provided runtimes, the binary name must be "bootstrap". This causes an issue with the way Lambda builders currently resolves the handler path for Go builds where the handler points to the correct source code location, but the binary is named incorrectly to be consumed by Lambda.
> fix: Rename provided go binary to bootstrap

- aws_lambda_builders/workflows/rust_cargo/cargo_lambda.py
- tests/integration/workflows/rust_cargo/test_rust_cargo.py
#634
This is to implement the workaround as fix as suggested in https://github.com/aws/aws-lambda-builders/issues/634
to support building lambda functions configured in a cargo workspace layout.
> fix: set CARGO_TARGET_DIR env var to support cargo workspace setup for sam build

- aws_lambda_builders/workflows/python_pip/packager.py
#624 
Update python glibc mapping to support newer versions of python for the scenario that a package needs to be built from source (e.g. llama-cpp)
> update _RUNTIME_GLIBC mapping to support newer python versions

- Makefile
- aws_lambda_builders/workflows/nodejs_npm/actions.py
- aws_lambda_builders/workflows/nodejs_npm/workflow.py
- pyproject.toml
https://github.com/aws/aws-lambda-builders/issues/635
- Adds logging to make it explicit that `sam build` only install production npm dependencies.
- Updates linting configuration to remove deprecated features
> chore: Improve npm install debug logging

- tests/integration/workflows/java_gradle/test_java_gradle.py
None.
Something changed within the runner environment, causing all Java Gradle tests to fail with the following error message:
```
* What went wrong:
Gradle could not start your build.
> Could not create service of type BuildLifecycleController using ServicesProvider.createBuildLifecycleController().
> Could not create service of type BuildModelController using VintageBuildControllerProvider.createBuildModelController().
> Could not create service of type OutputFilesRepository using ExecutionBuildServices.createOutputFilesRepository().
> java.io.IOException: Cannot delete file: C:\Users\RUNNER~1\AppData\Local\Temp\tmpale85rhe\gradle-cache\buildOutputCleanup\buildOutputCleanup.lock
```
I still don't know why this is the case, but we can …
> fix: Change the TEMP folder for Gradle tests to home for Windows

- aws_lambda_builders/workflows/java_gradle/gradle_validator.py
- tests/unit/workflows/java_gradle/test_gradle_validator.py
https://github.com/aws/aws-sam-cli/issues/7730
Since `gradle --version` could return this string
```
Daemon JVM:    /Library/Java/JavaVirtualMachines/amazon-corretto-21.jdk/Contents/Home (no JDK specified, using current Java home)
```
we should limit the search for JVM on `Launcher JVM:` and `JVM:` only.
> fix: Restrict the condition for Gradle JVM string 

- aws_lambda_builders/validator.py
- tests/integration/workflows/ruby_bundler/test_ruby.py
Add support for upcoming runtime Ruby 3.4 (`ruby3.4`)
Ruby 3.4 is coming soon: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-future
The tests are parameterized, so we don't need to add any custom code to test a new version of the runtime. 
> feat: Add support for Ruby 3.4

- aws_lambda_builders/workflows/python_pip/packager.py
*Issue #, if available:* #700
*Description of changes:* Lambdas using Python 3.12 or 3.13 as runtime use Amazon Linux 2023 instead of Amazon Linux 2 as per the [official AWS documentation](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-supported).
This PR updates the available GLIBC version to 2.34, as can be obtained by running the image in Docker
```shell
$ docker run --rm -it --entrypoint /bin/bash public.ecr.aws/lambda/provided:al2023
Unable to find image 'public.ecr.aws/lambda/provided:al2023' locally
al2023: Pulling from lambda/provided
...
Status: Downloaded newer image for public.ecr.aws/lambda/provided:al2023
bash-5.2# ldd --version
ldd (GNU libc) 2.34
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying …
```
> feat: update the GLIBC version available for Python 3.12 and 3.13

- Makefile
- aws_lambda_builders/workflows/python_pip/packager.py
- tests/functional/workflows/python_pip/test_packager.py
- tests/unit/workflows/python_pip/test_packager.py
*Issue:* #700
As described by @valerena [here](https://github.com/aws/aws-lambda-builders/issues/700#issuecomment-3049644352), when trying to build cross-architecture, the platform tags added to the pip command are not correct. With this PR, I've fixed the issue while preserving most of the original logic. The approach is to add all compatible platform tags for each python version and architecture pair to the pip command, as per the [official pip documentation](https://pip.pypa.io/en/stable/cli/pip_download/#cmdoption-platform).
The code may look a bit hacky, but I tried to change as few lines as possible. Feel free to propose improvements - I'm ready to accept them.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> feat: allow manylinux 2.28 and 2.34 on python 3.12+ when compiled on a different architecture

- aws_lambda_builders/builder.py
- aws_lambda_builders/workflow.py
- aws_lambda_builders/workflows/python_pip/DESIGN.md
- aws_lambda_builders/workflows/python_pip/actions.py
- aws_lambda_builders/workflows/python_pip/workflow.py
- tests/integration/workflows/python_pip/test_python_pip.py
- tests/unit/test_builder.py
- tests/unit/workflows/python_pip/test_actions.py
*Issue #, if available:* https://github.com/aws/aws-sam-cli/issues/6593
This change introduces a configuration option for the python lambda directory structure. I previously created a wrapper around sam cli to achieve this but would like to contribute the feature back to this project. The issue linked above and my [GitHub repo](https://github.com/Agnostella/samwich-cli/tree/main/docs#examples-and-advanced-usage) have examples and documentation that explain the goal of this change. Once implemented, I will need to submit a PR for aws-sam-cli as well to utilize this new optional config.
I welcome your criticism and suggestions; thank you for your time reviewing this PR.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> feat: add python option for creating parent packages during copy
