.travis.yaml
Makefile
aws_lambda_builders/__init__.py
aws_lambda_builders/actions.py
aws_lambda_builders/exceptions.py
aws_lambda_builders/registry.py
aws_lambda_builders/workflow.py
setup.py

Classes with nearly empty implementations that can be used to start building workflows

Base classes to help implementing python workflow

---

aws_lambda_builders/workflows/python_pip/DESIGN.md

Original file got accidentally deleted during a refactor.

Design doc for `python_pip` workflow. Copy of #5.

---

.appveyor.yml
.travis.yml

Don't run tests on py37

---

aws_lambda_builders/__init__.py

Bumping to v0.0.3

---

.appveyor.yml
.travis.yml
MANIFEST.in
aws_lambda_builders/__init__.py
aws_lambda_builders/exceptions.py
aws_lambda_builders/validate.py
aws_lambda_builders/workflows/python_pip/DESIGN.md
aws_lambda_builders/workflows/python_pip/actions.py
aws_lambda_builders/workflows/python_pip/compat.py
aws_lambda_builders/workflows/python_pip/packager.py
requirements/dev.txt
requirements/python_pip.txt
setup.py
tests/functional/workflows/python_pip/test_packager.py
tests/integration/workflows/python_pip/test_python_pip.py
tests/unit/test_runtime.py
tests/unit/workflows/python_pip/test_actions.py
tests/unit/workflows/python_pip/test_packager.py

Release v0.0.3

---

aws_lambda_builders/__init__.py

chore: 0.0.4 version bump

---

aws_lambda_builders/__init__.py

chore: 0.0.5 version bump

---

DESIGN.md

fixed relative path to design doc
didn't find one
fixed a relative path so that the link works

fix relative path

---

aws_lambda_builders/__init__.py

chore: version bump to 0.1.0

---

.gitignore
.travis.yml
aws_lambda_builders/workflows/__init__.py
aws_lambda_builders/workflows/dotnet_clipackage/DESIGN.md
aws_lambda_builders/workflows/dotnet_clipackage/__init__.py
aws_lambda_builders/workflows/dotnet_clipackage/actions.py
aws_lambda_builders/workflows/dotnet_clipackage/dotnetcli.py
aws_lambda_builders/workflows/dotnet_clipackage/dotnetcli_resolver.py
aws_lambda_builders/workflows/dotnet_clipackage/utils.py
aws_lambda_builders/workflows/dotnet_clipackage/workflow.py
tests/integration/workflows/dotnet_clipackage/test_dotnet.py
tests/integration/workflows/dotnet_clipackage/testdata/RequireParameters/RequireParameters.cs
tests/integration/workflows/dotnet_clipackage/testdata/RequireParameters/RequireParameters.csproj
tests/integration/workflows/dotnet_clipackage/testdata/WithDefaultsFile/Function.cs
tests/integration/workflows/dotnet_clipackage/testdata/WithDefaultsFile/WithDefaultsFile.csproj
tests/integration/workflows/dotnet_clipackage/testdata/WithDefaultsFile/aws-lambda-tools-defaults.json
tests/unit/workflows/dotnet_clipackage/test_actions.py
tests/unit/workflows/dotnet_clipackage/test_dotnetcli.py
tests/unit/workflows/dotnet_clipackage/test_dotnetcli_resolver.py
tests/unit/workflows/dotnet_clipackage/test_workflow.py

_Description of changes:_
Add support for building .NET Core Lambda function as part of SAM build.

Add support for .NET Core build

---

.appveyor.yml
aws_lambda_builders/workflows/__init__.py
aws_lambda_builders/workflows/java_maven/DESIGN.md
aws_lambda_builders/workflows/java_maven/__init__.py
aws_lambda_builders/workflows/java_maven/actions.py
aws_lambda_builders/workflows/java_maven/maven.py
aws_lambda_builders/workflows/java_maven/maven_resolver.py
aws_lambda_builders/workflows/java_maven/maven_validator.py
aws_lambda_builders/workflows/java_maven/utils.py
aws_lambda_builders/workflows/java_maven/workflow.py
tests/functional/workflows/java_maven/test_java_utils.py
tests/integration/workflows/java_maven/test_java_maven.py
tests/integration/workflows/java_maven/testdata/single-build/no-deps/pom.xml
tests/integration/workflows/java_maven/testdata/single-build/no-deps/src/main/java/aws/lambdabuilders/Main.java
tests/integration/workflows/java_maven/testdata/single-build/no-deps/src/main/resources/some_data.txt
tests/integration/workflows/java_maven/testdata/single-build/with-deps-broken/pom.xml
tests/integration/workflows/java_maven/testdata/single-build/with-deps-broken/src/main/java/aws/lambdabuilders/Main.java
tests/integration/workflows/java_maven/testdata/single-build/with-deps/pom.xml
tests/integration/workflows/java_maven/testdata/single-build/with-deps/src/main/java/aws/lambdabuilders/Main.java
tests/integration/workflows/java_maven/testdata/single-build/with-deps/src/main/resources/some_data.txt
tests/unit/workflows/java_maven/test_actions.py
tests/unit/workflows/java_maven/test_maven.py
tests/unit/workflows/java_maven/test_maven_resolver.py
tests/unit/workflows/java_maven/test_maven_validator.py
tests/unit/workflows/java_maven/test_workflow.py

Add design doc and implementations for Java Maven builder

---

aws_lambda_builders/__init__.py

chore: Release v0.2.1

---

aws_lambda_builders/__init__.py
aws_lambda_builders/__main__.py
aws_lambda_builders/builder.py
aws_lambda_builders/workflow.py
aws_lambda_builders/workflows/dotnet_clipackage/actions.py
aws_lambda_builders/workflows/dotnet_clipackage/workflow.py
tests/unit/test_builder.py
tests/unit/workflows/dotnet_clipackage/test_actions.py

Still thinking through some of the interactions between this and SAM CLI but sending this for early feedback.

feat(debug): DotNetCore support for producing debug artifacts

---

aws_lambda_builders/__init__.py

Bumping version to 0.3.0

---

aws_lambda_builders/__init__.py
aws_lambda_builders/__main__.py
aws_lambda_builders/builder.py
aws_lambda_builders/workflow.py
aws_lambda_builders/workflows/dotnet_clipackage/actions.py
aws_lambda_builders/workflows/dotnet_clipackage/workflow.py
aws_lambda_builders/workflows/java_gradle/gradle_validator.py
aws_lambda_builders/workflows/java_maven/maven_validator.py
tests/unit/test_builder.py
tests/unit/workflows/dotnet_clipackage/test_actions.py
tests/unit/workflows/java_gradle/test_gradle_validator.py
tests/unit/workflows/java_maven/test_maven_validator.py

0.3.0 release

---

README.md

fix: add content to README

---

LICENSE

fix: add current year into LICENSE

---

aws_lambda_builders/__init__.py

chore: Bumping version to 0.4.0

---

aws_lambda_builders/__init__.py

chore: bump version to 0.5.0

---

README.md

fix: appveyor build badge

---

aws_lambda_builders/__init__.py

chore: version bump

---

.appveyor.yml
aws_lambda_builders/workflows/go_modules/validator.py
tests/functional/workflows/python_pip/test_packager.py
tests/unit/workflows/go_modules/test_validator.py

Allow building Go Modules with release candidate versions of Go.

fix(modules): Allow building with rc go versions

---

aws_lambda_builders/__init__.py

chore: Version Bump to 0.8.0

---

aws_lambda_builders/__init__.py

chore: version bump to 0.9.0

---

aws_lambda_builders/__init__.py
requirements/dev.txt
tests/integration/workflows/custom_make/test_custom_make.py

chore: Version bump to 1.0.0

---

aws_lambda_builders/__init__.py

chore: bump version to 1.1.0

---

aws_lambda_builders/__init__.py

chore: bump version to 1.2.0

---

aws_lambda_builders/__init__.py

Bump lambda builders version to 1.3.0

---

aws_lambda_builders/__init__.py

chore: Bump lambda builders version to 1.4.0

---

.appveyor.yml
aws_lambda_builders/__init__.py
aws_lambda_builders/workflows/go_modules/builder.py
aws_lambda_builders/workflows/java_maven/maven.py
aws_lambda_builders/workflows/python_pip/packager.py
tests/functional/workflows/python_pip/test_packager.py
tests/integration/workflows/java_maven/test_java_maven.py
tests/integration/workflows/python_pip/test_python_pip.py
tests/integration/workflows/python_pip/testdata/requirements-numpy.txt
tests/unit/workflows/go_modules/test_builder.py
tests/unit/workflows/java_maven/test_maven.py
tests/unit/workflows/python_pip/test_packager.py

Merge develop to master

---

README.md

docs: README - showcase Makefile support

---

.appveyor.yml

chore: Update AppVeyor image from VS2017 to VS2019

---

aws_lambda_builders/__init__.py

chore: bump version to 1.5.0

---

aws_lambda_builders/__init__.py

chore: bump aws-lambda-builder version to 1.6.0

---

aws_lambda_builders/__init__.py
aws_lambda_builders/workflows/go_modules/validator.py
aws_lambda_builders/workflows/python_pip/packager.py
aws_lambda_builders/workflows/python_pip/utils.py
tests/functional/workflows/python_pip/test_packager.py
tests/unit/test_workflow.py
tests/unit/workflows/go_modules/test_validator.py

Merge from develop to master

---

aws_lambda_builders/__init__.py

chore: bump version to 1.8.0

---

aws_lambda_builders/exceptions.py
aws_lambda_builders/workflows/custom_make/validator.py
aws_lambda_builders/workflows/custom_make/workflow.py
aws_lambda_builders/workflows/go_modules/validator.py
tests/unit/test_workflow.py

fix: CustomMake validator

---

aws_lambda_builders/__init__.py
aws_lambda_builders/workflows/go_modules/validator.py

chore: bump version to 1.8.1

---

aws_lambda_builders/__init__.py

chore: bump version to 1.10.0

---

aws_lambda_builders/__init__.py

chore: bump version to 1.11.0

---

aws_lambda_builders/__main__.py
tests/functional/test_cli.py

Read additional fields passed down to lambda builders.

fix: Read feature flags from params

---

aws_lambda_builders/__init__.py

chore: Version bump 1.12.0

---

aws_lambda_builders/__init__.py
aws_lambda_builders/__main__.py
aws_lambda_builders/actions.py
aws_lambda_builders/workflows/nodejs_npm_esbuild/actions.py
aws_lambda_builders/workflows/nodejs_npm_esbuild/esbuild-plugin.js.template
aws_lambda_builders/workflows/nodejs_npm_esbuild/node.py
aws_lambda_builders/workflows/nodejs_npm_esbuild/workflow.py
tests/functional/test_cli.py
tests/integration/test_actions.py
tests/integration/workflows/nodejs_npm_esbuild/test_nodejs_npm_with_esbuild.py
tests/integration/workflows/nodejs_npm_esbuild/testdata/with-deps-no-node_modules/excluded.js
tests/integration/workflows/nodejs_npm_esbuild/testdata/with-deps-no-node_modules/included.js
tests/integration/workflows/nodejs_npm_esbuild/testdata/with-deps-no-node_modules/package.json
tests/unit/workflows/nodejs_npm_esbuild/test_actions.py
tests/unit/workflows/nodejs_npm_esbuild/test_node.py
tests/unit/workflows/nodejs_npm_esbuild/test_workflow.py

chore: Merge develop into master

---

aws_lambda_builders/__init__.py

Version bump to 1.13.0

---

aws_lambda_builders/__init__.py

chore: Version bump to 1.14.0

---

aws_lambda_builders/__init__.py

chore: Version bump to 1.15.0

---

aws_lambda_builders/__init__.py

Version bump to 1.16.0

---

aws_lambda_builders/__init__.py

chore: bump version to 1.17.0

---

tests/unit/test_actions.py

fix: Convert stream to list before assertion

---

aws_lambda_builders/__init__.py

N.A.
Update version number for lambda builder release

chore: bump version to 1.18.0

---

aws_lambda_builders/workflows/nodejs_npm_esbuild/esbuild.py
tests/unit/workflows/nodejs_npm_esbuild/test_esbuild.py

https://github.com/aws/aws-sam-cli/issues/4093
Add support for --main-fields option.

feat: Add support for --main-fields esbuild option

---

aws_lambda_builders/__init__.py

chore: bump version to 1.20.0

---

aws_lambda_builders/__init__.py

chore: version bump to 1.21.0

---

aws_lambda_builders/__init__.py

chore: version bump to 1.22.0

---

aws_lambda_builders/__init__.py

chore: bump version to 1.23.0

---

aws_lambda_builders/__init__.py

Bumping version to release a bunch of fixes

Version bump

---

aws_lambda_builders/__init__.py

chore: Version bump to 1.25.0

---

aws_lambda_builders/__init__.py

chore: bump version to 1.26.0

---

aws_lambda_builders/__init__.py

chore: version bump to v1.27.0

---

aws_lambda_builders/__init__.py

chore: bump version to 1.29.0

---

aws_lambda_builders/__init__.py

chore: bump version to 1.30.0

---

.github/labeler.yml

n/a
Fix small typo in a path in labeler config.

Fix path typo in labeler

---

aws_lambda_builders/__init__.py

chore: version bump to 1.31.0

---

aws_lambda_builders/__init__.py

Bump Lambda builder package version to 1.34.0

chore: Version bump to 1.34.0

---

aws_lambda_builders/__init__.py

Version bump from 1.35.0 to 1.36.0.

chore: Bump version to 1.36.0

---

aws_lambda_builders/__init__.py

chore: Version bump to 1.37.0

---

aws_lambda_builders/__init__.py

chore: Version Bump 1.38.0

---

aws_lambda_builders/__init__.py

chore: Version bump to 1.39.0

---

aws_lambda_builders/__init__.py

chore: Version bump to 1.40.0

---

.github/workflows/build.yml

See https://github.com/aws/aws-sam-cli/pull/6203

fix: update root GHA definition

---

aws_lambda_builders/__init__.py

chore: Version bump to 1.42.0

---

aws_lambda_builders/__init__.py

None.
Bumps the version of Lambda Builders to the next version.

chore: Bump Lambda Builders version to 1.43.0

---

.github/labeler.yml
.github/workflows/pr-labeler.yml

bumps actions/labeler from 4 to 5

chore(deps): bump actions/labeler from 4 to 5

---

aws_lambda_builders/__init__.py

chore: bump version to 1.45.0

---

aws_lambda_builders/__init__.py

chore: Bump version to 1.47.0

---

aws_lambda_builders/validator.py
tests/integration/workflows/ruby_bundler/test_ruby.py

Adding Ruby3.3. Runtime Support 

feat: add ruby3.3 support

---

aws_lambda_builders/__init__.py

Bump version to 1.48.0

---

aws_lambda_builders/__init__.py

chore: bump version to 1.50.0

---

aws_lambda_builders/__init__.py

chore: version bump to 1.52.0

---

aws_lambda_builders/__init__.py

chore: Bump Lambda Builders to 1.53.0

---

.github/dependabot.yml
CODEOWNERS

Add Tooling team to code owners

---

aws_lambda_builders/__init__.py

Change the version to trigger a new release

chore: version bump to 1.54.0

---

CODEOWNERS

N/A
Removing SBT team from the CODEOWNERS file.

chore: remove SBT team from CODEOWNERS

---

aws_lambda_builders/__init__.py

*Issue #, if available:* #700
*Description of changes:* Change the version to trigger a new release to release #752 

chore: version bump to 1.55.0

---

aws_lambda_builders/__init__.py

*Issue #, if available:* #700
Release new version with changes in #762

chore: version bump to 1.56.0
